name: Build boot.image

on:
  workflow_dispatch:
    inputs:
      release:
          description: 'Upload release'
          type: boolean
          required: true
          default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository with submodules (shallow clone)
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 1

      - name: Install build tools
        run: |
          sudo apt-get install -y \
            build-essential \
            git \
            curl \
            unzip \
            wget \
            zip

      # 2. Run your custom bash script
      - name: Build kernel
        run: |
          chmod +x build.sh
          bash build.sh
          cd ..

      - name: Generate release version
        id: ts
        run: |
          echo "RELEASE_TS=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
          : > version.txt
          echo "**Kernel version:** $(cat kernel/out/include/config/kernel.release)  " >> version.txt
          echo >> version.txt
          cd kernel
          export KHASH="$(git rev-parse HEAD)"
          cd ..
          echo "**Kernel source:** [$KHASH](https://github.com/UN1CA/kernel_samsung_sm7150/tree/$KHASH)" >> version.txt


      # 3. Upload the generated boot.img
      - name: Upload boot.img artifact
        uses: actions/upload-artifact@v5
        with:
          name: boot-image
          path: boot.img

      - name: Upload release assets
        if: github.event.inputs.release
        uses: softprops/action-gh-release@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          body_path: version.txt
          tag_name: "${{ env.RELEASE_TS }}"
          name: "ParadigmKernel-${{ env.RELEASE_TS }}"
          files: |
            boot.img
            dtbo.img
