name: Build boot.image

on:
  workflow_dispatch:
    inputs:
      release:
          description: 'Upload release'
          type: boolean
          required: true
          default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository with submodules (shallow clone)
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 1

      - name: Cleanup space
        run: |
          sudo apt-get remove --purge -y "php*" "dotnet*" "mysql*" "nodejs*" "clang*" "google*"
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /usr/local

      - name: Install build tools
        run: |
          sudo apt-get install -y \
            build-essential \
            git \
            curl \
            unzip \
            wget \
            zip

      - name: Download prebuilt Google clang
        run: |
          cd kernel
          wget -O llvm.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main-kernel-2025/clang-r547379.tar.gz
          mkdir llvm-20; cd llvm-20
          tar xvzf ../llvm.tar.gz
          rm ../llvm.tar.gz
          cd ..

      # 2. Run your custom bash script
      - name: Run build script
        run: |
          mv ../build_kernel.sh build_kernel.sh
          chmod +x build_kernel.sh
          bash build_kernel.sh
          cd ..

      - name: Build boot image
        run: |
          chmod +x build_boot.sh
          bash build_boot.sh

      - name: Generate release version
        id: ts
        run: |
          echo "RELEASE_TS=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
          echo "REL_VER=Kernel version: $(cat kernel/out/include/config/kernel.release)" >> $GITHUB_ENV


      # 3. Upload the generated boot.img
      - name: Upload boot.img artifact
        uses: actions/upload-artifact@v5
        with:
          name: boot-image
          path: boot.img

      - name: Upload release assets
        if: github.event.inputs.release
        uses: softprops/action-gh-release@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          body: "${{ env.REL_VER }}"
          tag_name: "${{ env.RELEASE_TS }}"
          name: "ParadigmKernel-${{ env.RELEASE_TS }}"
          files: |
            boot.img
            dtbo.img
